apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      nodeSelector:
        arch: arm64
      serviceAccountName: k8sapigetter
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: igoroschsimoes/loadgen:v4arm
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 1280Mi
          limits:
            cpu: 1000m
            memory: 3000Mi        